### ISSUE TITLE
Rearrange rand later.

### ISSUE THREAD

**Issue by RCasatta** [ElementsProject/rust-elements#149]
I think for now let's just go with this, since it's blocking our move to `rand 0.8`. We can rearrange things later.

_Originally posted by @apoelstra in https://github.com/ElementsProject/rust-elements/pull/148#discussion_r984035681_

What do we want to do?
* Reintroduce rand again and remove CrappyRng
* Move examples to tests/
* Something else

**Comment by apoelstra** [comment]
I think we should actually reintroduce `rand-chacha` as a dev-dependency and use that rather than CrappyRng.

Alternately we could expose our own chacha impl from secp-zkp, but that would be kinda involved and I don't know if we want to commit to doing that.

**Comment by RCasatta** [comment]
I was starting to do this, however, I have a doubt.

```
let mut rng = rand_chacha::ChaCha20Rng::seed_from_u64(0); 
```

is probably more dangerous than

```
let mut rng = CrappyRng::new(core::num::NonZeroU64::new(1).unwrap());
```

In the first case, you may think to go into production with 
```
let mut rng = rand_chacha::ChaCha20Rng::seed_from_u64(random());  
```
Which is not secure because the input is only 64 bits.

while I don't think you go into production with `CrappyRng`
