### ISSUE TITLE
WIF

### ISSUE THREAD

**Issue by uncomputable** [ElementsProject/rust-elements#158]
Is the [wallet import format](https://en.bitcoin.it/wiki/Wallet_import_format) defined for Elements? The generation involves prepending a byte that signifies the network. For Elements, is there something similar for the different address parameters? If so, then this method is currently missing.

WIF would be useful for importing output descriptors. I could write a PR that [mimics rust-bitcoin](https://docs.rs/bitcoin/latest/bitcoin/key/struct.PrivateKey.html#method.to_wif).

**Comment by uncomputable** [comment]
I found out the definition, but Elements uses `bitcoin::PublicKey` and `bitcoin::SecretKey`. Adding a custom WIF method would mean writing a custom `elements::SecretKey`, which seems a bit much.

Unless we want to do the extra work, let's close the issue. The following code is a workaround:

```
let network = match params {
    &AddressParams::LIQUID => bitcoin::Network::Bitcoin,
    _ => bitcoin::Network::Regtest,
};
let priv = bitcoin::PrivateKey::new(secret_key, network);
```

**Comment by apoelstra** [comment]
Well, if we need elements WIF keys we should add support .... but what are you doing with WIF private keys?
