### ISSUE TITLE
What is the rationale behind `Value::Null`?

### ISSUE THREAD

**Issue by thomaseizinger** [ElementsProject/rust-elements#63]
I am currently working with the `elements` library and was wondering, what the rationale is for having a `Value::Null` variant?

What is the edge-case that we are covering here?

**Comment by sanket1729** [comment]
The only place `Value::Null` is used in `AssetIssuance` where the `nInflationKeys` can be `Value::Null`.

**Comment by thomaseizinger** [comment]
Okay, thank you!
